[program:jupyter]
; command=/usr/sbin/sshd -D
command=/usr/local/bin/jupyterhub --config=/etc/jupyter/jupyterhub_config.py
autostart=true
autorestart=true
stderr_logfile=/var/log/jupyterhub.err.log
stdout_logfile=/var/log/jupyterhub.out.log
user=root
