# WebSocket含むリバースプロキシ
ProxyPreserveHost On
# ProxyPass        /jupyter http://127.0.0.1:8000/jupyter retry=0
# ProxyPassReverse /jupyter http://127.0.0.1:8000/jupyter
ProxyPass        /jupyter/ http://127.0.0.1:8000/jupyter/
ProxyPassReverse /jupyter/ http://127.0.0.1:8000/jupyter/
# ProxyPass        /jupyter/ ws://127.0.0.1:8000/jupyter/ retry=0
ProxyPass        /jupyter/ ws://127.0.0.1:8000/jupyter/

# RewriteEngine On
# RewriteCond %{HTTP:Upgrade} =websocket [NC]
# RewriteRule /jupyter/(.*) ws://127.0.0.1:8000/jupyter/$1 [P,L]
