RewriteEngine On
RewriteMap user2port prg:/usr/local/bin/user2port.sh
RewriteRule ^/user/([^/]+)(.*) http://localhost:${user2port:$1}$2 [P,L]

# RewriteRule /port/(.*)  http://edulinux:$1 [P,L]
# ProxyPassMatch ^/port/([0-9]+)/(.*)$ http://localhost:$1/$2
# ProxyPassReverse ^/port/([0-9]+)/(.*)$ http://localhost:$1/$2
