# WebSocket含むリバースプロキシ
ProxyPreserveHost On
ProxyPass        /ttyd/  http://localhost:7681/
ProxyPassReverse /ttyd/  http://localhost:7681/

# WebSocket対応（ttydはWSを使う）
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /ttyd/(.*)  ws://localhost:7681/$1 [P,L]

AddExternalAuth pwauth /usr/sbin/pwauth
SetExternalAuthMethod pwauth pipe

<Location /ttyd/>
    AuthType Basic
    AuthName "ttyd login"
    AuthBasicProvider external
    AuthExternal pwauth
    Require valid-user
    RequestHeader set X-REMOTE-USER %{REMOTE_USER}s
</Location>
