[program:sshd]
; command=/usr/sbin/sshd -D
command=bash -c 'mkdir -p /run/sshd && chmod 755 /run/sshd && /usr/sbin/sshd -D'
autostart=true
autorestart=true
stderr_logfile=/var/log/sshd.err.log
stdout_logfile=/var/log/sshd.out.log
user=root
