[sssd]
config_file_version = 2
services = nss, pam
domains = default

[domain/default]
# ドメインの種類を最初に宣言
id_provider = ldap
auth_provider = ldap
access_provider = permit

# 接続先 (先ほど nc で成功した IP とポートを指定)
ldap_uri = ldap://ldap
# ldap_uri = ldaps://ldap
ldap_search_base = dc=example,dc=local

# 匿名検索を許可していない場合、以下の2行が必須です
ldap_default_bind_dn = cn=admin,dc=example,dc=local
ldap_default_authtok = ${LDAP_ADMIN_PASSWORD}

# ldap_id_use_start_tls = True
# ldap_tls_reqcert = demand
# TLS設定 (まずは疎通を優先して一度切ります)
ldap_id_use_start_tls = False
ldap_tls_reqcert = never

# 余計な機能を無効化してエラーを減らす
sudo_provider = none
dns_discovery_domain = none
enumerate = False

# サーバーを「故障」と判定する基準を緩くし、すぐに再試行させる
# first_pass_check_type = initial
dns_discovery_domain = none
# タイムアウトを少し伸ばす
ldap_network_timeout = 15
# オフライン状態からの復帰を早める
offline_timeout = 1

# ldap_auth_disable_tls_never_use_in_production = True
