[sssd]
config_file_version = 2
services = nss, pam
domains = default

[domain/default]
id_provider = ldap
auth_provider = ldap
ldap_uri = ldap://ldap.internal
ldap_search_base = dc=example,dc=local

# 最小限の認証設定
ldap_default_bind_dn = cn=admin,dc=example,dc=local
ldap_default_authtok = ${LDAP_ADMIN_PASSWORD}

# TLSを「使わない」ための最も標準的な設定のみ残す
# ldap_id_use_start_tls = False
ldap_id_use_start_tls = True
# ldap_tls_reqcert = never
# ldap_tls_reqcert = allow
ldap_tls_reqcert = demand
ldap_tls_cacert = /etc/sssd/certs/ca.crt

# TLSの最小バージョンを 1.2 に固定してみる
# ldap_tls_cipher_suite = HIGH:!NULL:!MD5
# ldap_tls_cipher_suite = HIGH:MEDIUM
ldap_tls_cipher_suite = NORMAL:-VERS-TLS1.3
