# WebSocket含むリバースプロキシ
ProxyPreserveHost On
ProxyPass        /ttyd/  http://edulinux:7681/
ProxyPassReverse /ttyd/  http://edulinux:7681/

# WebSocket対応（ttydはWSを使う）
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /ttyd/(.*)  ws://edulinux:7681/$1 [P,L]
RewriteRule /port/(.*)  http://edulinux:$1/ [P,L]

# RequestHeader set X-Forwarded-Proto "https"
