services:
  ldap:
    image: osixia/openldap
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "Example Inc"
      LDAP_DOMAIN: "example.local"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    ports:
      - "389:389"

  lam:
    image: ldapaccountmanager/lam:latest
    container_name: lam
    environment:
      LAM_LANG: ja_JP
    ports:
      - "8080:80"
    depends_on:
      - ldap
      