[program:postfix]
command=/usr/sbin/postfix start-fg
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/postfix.err.log
stdout_logfile=/var/log/supervisor/postfix.out.log
user=root

[program:dovecot]
command=/usr/sbin/dovecot -F
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/dovecot.err.log
stdout_logfile=/var/log/supervisor/dovecot.out.log
user=root
